### ISSUE TITLE
Can you update this?

### ISSUE THREAD

**Issue by cyberlimbo** [zybeon/RustOxideAutoUpdater#1]
Hi

Can you update this?
*I recommend you to test everything cause there are several errors / mistakes.

Example: 

_mkdir /opt/RustOxideAutoUpdater_                
(This is useless cause the git command will create a "RustOxideAutoUpdate" folder)

_cd RustOxideAutoUpdater_                           
(Correct = cd /opt/RustOxideAutoUpdater)

_git clone https://github.com/zybeon/RustOxideAutoUpdater.git_ 
(This will create another "RustOxideAutoUpdate" folder inside the "RustOxideAutoUpdate" folder)

I think the correct way to install is:

cd /opt
git clone https://github.com/zybeon/RustOxideAutoUpdater.git
cd /RustOxideAutoUpdater
npm i webrconjs

Another thing..  when running the script:

_Starting . . .
Downloading Latest Oxide version info
installedOxide.txt already exists, checking for update
New update is available!
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/opt/RustOxideUpdater/node_modules/webrconjs/webrconjs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/RustOxideAutoUpdater/rustrconsend.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)_

Any solution?
Thanks for the script (but i i'm still trying to make it work xD)

**Comment by cyberlimbo** [comment]
I just found the lgsm mod thing that basically do everything.
Thanks anyway ;)
